name: de_src
description: A library for deepseek reverse call. Named `DeSrc`.
version: 1.0.0
home: https://dudu.ltd
repository: https://github.com/dudu-ltd/deepseek-reverse-call

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # yaml: ^3.1.3
  # reflectable: ^4.0.9
  # deepseek: ^1.0.1
  openai_dart: ^0.4.5
  interpolation: ^2.1.2
  logger: ^2.0.2+1
  json5: ^0.8.2
  http: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
