spring:
  application:
    name: deepseek-reverse-call-discuss
  profiles:
    active: dev

deepseek:
  base-url: https://api.deepseek.com
  #  https://platform.deepseek.com/api_keys
  api-key: <API_KEY>
  model: deepseek-chat
  log-requests: true
  log-responses: true
  log-level: DEBUG


logging:
  level:
    ltd.dudu.dsrc: DEBUG